# Generated by Django 4.2.16 on 2024-10-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_completed_at_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='work', max_length=100),
        ),
    ]
